version: '3.5'

services: 
  postgres:
    container_name: composepostgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB_NAME: postgres
      POSTGRES_SCHEMA: pismo
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped

  app:
    build: ./../.
    environment:
      - POSTGRES_HOST=composepostgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=postgres
      - POSTGRES_SCHEMA=pismo
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=postgres
    ports:
      - 3000:3000
    networks:
      - postgres
    depends_on:
      - postgres
  
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
